# Generated by Django 4.1.3 on 2022-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.SlugField(default='', editable=False, max_length=100, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Unanswered'), (1, 'Answered')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('answered_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
