# Generated by Django 4.1.3 on 2022-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qboxapp', '0002_remove_question_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unanswered'), (1, 'Answered')], default=0),
        ),
    ]
